{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nodejs-app.fullname" . }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ (index .Values.ingress.hosts 0).host | quote }}
      http:
        paths:
          {{- range $path := (index .Values.ingress.hosts 0).paths }}
          - path: {{ $path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "nodejs-app.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          {{- end }}
{{- end }}

