# Default values for the nodejs-app chart
replicaCount: 1
image:
  repository: your-registry/your-image
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

